// ===================== STATE MODULE =====================
// Gerencia o estado global da aplicação

const state = {
  calendario: [
    {mes:"janeiro",data:"24/01",dia:"sáb.",atividade:"Indaba de Chefes",categoria:"",chefe:"",datas:"",obs:""},
    {mes:"janeiro",data:"31/01",dia:"sáb.",atividade:"Início das Atividades/Normal Sede",categoria:"",chefe:"",datas:"",obs:""},
    {mes:"fevereiro",data:"07/02",dia:"sáb.",atividade:"Normal Sede - Recepcao Novos",categoria:"",chefe:"",datas:"",obs:"EVENTO ASSOCIACAO: Yokai Festival"},
    {mes:"fevereiro",data:"14/02",dia:"sáb.",atividade:"Emenda - Feriado Carnaval",categoria:"",chefe:"",datas:"",obs:""},
    {mes:"fevereiro",data:"16/02",dia:"seg.",atividade:"Feriado Carnaval",categoria:"",chefe:"",datas:"",obs:""},
    {mes:"fevereiro",data:"17/02",dia:"ter.",atividade:"Feriado Carnaval",categoria:"",chefe:"",datas:"",obs:""},
    {mes:"fevereiro",data:"18/02",dia:"qua.",atividade:"Feriado Carnaval",categoria:"",chefe:"",datas:"",obs:""},
    {mes:"fevereiro",data:"21/02",dia:"sáb.",atividade:"Normal Sede (Passagem Lobinhos)",categoria:"",chefe:"Marly e Julia",datas:"",obs:"BAILE ASSOCIACAO"},
    {mes:"fevereiro",data:"28/02",dia:"sáb.",atividade:"Normal Sede/Habilidades Escoteiras/Transiçao Lobinho",categoria:"",chefe:"Sampei e Mariana",datas:"",obs:"CT Vivência Lobinho (28 a 1/03)"},
    {mes:"março",data:"07/03",dia:"sáb.",atividade:"Normal Sede",categoria:"",chefe:"Carol e Juliana",datas:"8 - Dia Internacional da Mulher",obs:""},
    {mes:"março",data:"14/03",dia:"sáb.",atividade:"Externa (Cinema)",categoria:"",chefe:"Angelita e Jefferson",datas:"Início MUTEPT",obs:""},
    {mes:"março",data:"15/03",dia:"dom.",atividade:"Festa do Sorvete",categoria:"Local",chefe:"",datas:"",obs:""},
    {mes:"março",data:"21/03",dia:"sáb.",atividade:"Normal Sede",categoria:"",chefe:"Marly e Julia",datas:"21 - Dia Internacional das Florestas / 22 - Dia Mundial da Água / 23 - Hora do Planeta",obs:"BAILE ASSOCIACAO"},
    {mes:"março",data:"28/03",dia:"sáb.",atividade:"Normal Sede/Habilidades Escoteiras/Transiçao Lobinho",categoria:"",chefe:"Sampei e Mariana",datas:"27 - Dia do circo",obs:""},
    {mes:"abril",data:"03/04",dia:"sex.",atividade:"Feriado Páscoa",categoria:"",chefe:"",datas:"",obs:""},
    {mes:"abril",data:"04/04",dia:"sáb.",atividade:"Emenda - Feriado Páscoa",categoria:"",chefe:"",datas:"",obs:""},
    {mes:"abril",data:"11/04",dia:"sáb.",atividade:"Externa - Caçada Distrital",categoria:"Distrital",chefe:"Todos",datas:"13 - Dia do Hino Nacional",obs:""},
    {mes:"abril",data:"18/04",dia:"sáb.",atividade:"Normal Sede (Reunião Acampamento)",categoria:"",chefe:"Carol e Juliana",datas:"18 - Dia Nacional do Livro Infantil / 19 - Dia do índio",obs:""},
    {mes:"abril",data:"21/04",dia:"ter.",atividade:"Feriado Tiradentes",categoria:"",chefe:"",datas:"22 - Dia da Terra",obs:""},
    {mes:"abril",data:"25/04",dia:"sáb.",atividade:"Normal sede/Transiçao Lobinho",categoria:"",chefe:"Angelita e Jefferson",datas:"",obs:"BAILE ASSOCIACAO"},
    {mes:"maio",data:"01/05",dia:"sex.",atividade:"Acampamento de Grupo",categoria:"Local",chefe:"Todos",datas:"",obs:""},
    {mes:"maio",data:"02/05",dia:"sáb.",atividade:"Acampamento de Grupo",categoria:"",chefe:"Todos",datas:"Início EducAÇÃO Escoteira",obs:""},
    {mes:"maio",data:"03/05",dia:"dom.",atividade:"Acampamento de Grupo",categoria:"",chefe:"Todos",datas:"",obs:""},
    {mes:"maio",data:"09/05",dia:"sáb.",atividade:"Normal Sede (Dia do Amigo)",categoria:"",chefe:"Marly e Julia",datas:"",obs:""},
    {mes:"maio",data:"16/05",dia:"sáb.",atividade:"Externa (a confirmar)",categoria:"",chefe:"Sampei e Mariana",datas:"15 - Dia Internacional da Família",obs:"BAILE ASSOCIACAO"},
    {mes:"maio",data:"23/05",dia:"sáb.",atividade:"Noite Escoteira Italiana",categoria:"Local",chefe:"Todos",datas:"22 - Dia do Abraço",obs:""},
    {mes:"maio",data:"30/05",dia:"sáb.",atividade:"Normal Sede/Habilidades Escoteiras",categoria:"",chefe:"Carol e Juliana",datas:"Fim EducAÇÃO Escoteira / Fim MutEPT",obs:""},
    {mes:"junho",data:"04/06",dia:"qui.",atividade:"Jangalcamp",categoria:"Regional",chefe:"",datas:"",obs:"Feriado Corpus Christi"},
    {mes:"junho",data:"05/06",dia:"sex.",atividade:"Jangalcamp",categoria:"",chefe:"",datas:"5 - Dia Mundial do Meio Ambiente",obs:""},
    {mes:"junho",data:"06/06",dia:"sáb.",atividade:"Jangalcamp",categoria:"",chefe:"",datas:"Início MutECO",obs:""},
    {mes:"junho",data:"07/06",dia:"dom.",atividade:"Jangalcamp",categoria:"",chefe:"",datas:"",obs:""},
    {mes:"junho",data:"13/06",dia:"sáb.",atividade:"Normal sede/Transiçao Lobinho",categoria:"",chefe:"Angelita e Jefferson",datas:"",obs:""},
    {mes:"junho",data:"20/06",dia:"sáb.",atividade:"Externa (a confirmar)",categoria:"",chefe:"Carol e Juliana",datas:"20 -Dia Internacional da Amizade",obs:"BAILE ASSOCIACAO Intermediário Lobinho (Distrito) - 27 e 28"},
    {mes:"junho",data:"27/06",dia:"sáb.",atividade:"Normal Sede/Habilidades Escoteiras",categoria:"",chefe:"Marly e Julia",datas:"26 - Dia dos Avós / Fim MutECO",obs:"Evento: WKS Cult Ainu de Hokkaido"},
    {mes:"julho",data:"04/07",dia:"sáb.",atividade:"Fogo de Conselho",categoria:"Local",chefe:"",datas:"",obs:""},
    {mes:"julho",data:"10/07",dia:"sex.",atividade:"Festival do Japão",categoria:"Local",chefe:"",datas:"",obs:""},
    {mes:"julho",data:"11/07",dia:"sáb.",atividade:"Festival do Japão",categoria:"Local",chefe:"",datas:"",obs:""},
    {mes:"julho",data:"12/07",dia:"dom.",atividade:"Festival do Japão",categoria:"Local",chefe:"",datas:"",obs:""},
    {mes:"agosto",data:"01/08",dia:"sáb.",atividade:"Normal Sede",categoria:"",chefe:"Marly e Julia",datas:"",obs:""},
    {mes:"agosto",data:"08/08",dia:"sáb.",atividade:"Normal Sede - recepcao novos",categoria:"",chefe:"Sampei e Mariana",datas:"12 - Dia Nacional das Artes",obs:""},
    {mes:"agosto",data:"15/08",dia:"sáb.",atividade:"Normal Sede",categoria:"",chefe:"Carol e Juliana",datas:"",obs:"Intermediário Lobinho (CEJ) - 15 e 16"},
    {mes:"agosto",data:"22/08",dia:"sáb.",atividade:"Externa (a confirmar)",categoria:"",chefe:"Angelita e Jefferson",datas:"22 - Dia do Folclore",obs:"BAILE ASSOCIACAO"},
    {mes:"agosto",data:"29/08",dia:"sáb.",atividade:"Normal Sede/Habilidades Escoteiras",categoria:"",chefe:"Marly e Julia",datas:"",obs:""},
    {mes:"setembro",data:"05/09",dia:"sáb.",atividade:"Acanto",categoria:"",chefe:"Todos",datas:"Início MutCOM",obs:""},
    {mes:"setembro",data:"06/09",dia:"dom.",atividade:"Acanto",categoria:"",chefe:"Todos",datas:"",obs:""},
    {mes:"setembro",data:"07/09",dia:"seg.",atividade:"Acanto",categoria:"",chefe:"Todos",datas:"",obs:""},
    {mes:"setembro",data:"12/09",dia:"sáb.",atividade:"Normal Sede",categoria:"",chefe:"Sampei e Mariana",datas:"",obs:"BAILE ASSOCIACAO Intermediário Lobinho (Distrito) - 12 e 13"},
    {mes:"setembro",data:"19/09",dia:"sáb.",atividade:"Normal Sede",categoria:"",chefe:"Carol e Juliana",datas:"21 - Dia da Árvore",obs:""},
    {mes:"setembro",data:"26/09",dia:"sáb.",atividade:"Normal Sede/Habilidades Escoteiras",categoria:"",chefe:"Angelita e Jefferson",datas:"Fim MutCOM",obs:"Avançado Lobinho 1 (CEJ) 26 e 27"},
    {mes:"outubro",data:"03/10",dia:"sáb.",atividade:"Externa - Rally de Lobinhos",categoria:"Distrital",chefe:"Todos",datas:"1 - Dia Internacional da Música / 4 -Dia dos Animais",obs:""},
    {mes:"outubro",data:"10/10",dia:"sáb.",atividade:"Emenda Feriado",categoria:"",chefe:"",datas:"",obs:""},
    {mes:"outubro",data:"12/10",dia:"seg.",atividade:"Feriado Nossa Senhora Aparecida",categoria:"",chefe:"",datas:"Dia das Crianças",obs:""},
    {mes:"outubro",data:"17/10",dia:"sáb.",atividade:"Preparaçao Scout Matsuri (JOTA-JOTI)",categoria:"Local",chefe:"Todos",datas:"",obs:""},
    {mes:"outubro",data:"18/10",dia:"dom.",atividade:"Scout Matsuri",categoria:"Local",chefe:"Todos",datas:"",obs:""},
    {mes:"outubro",data:"24/10",dia:"sáb.",atividade:"Normal Sede (Dia do Amigo)",categoria:"",chefe:"Marly e Julia",datas:"",obs:"BAILE ASSOCIACAO"},
    {mes:"outubro",data:"31/10",dia:"sáb.",atividade:"Emenda Feriado",categoria:"",chefe:"",datas:"Halloween",obs:""},
    {mes:"novembro",data:"02/11",dia:"seg.",atividade:"Feriado Finados",categoria:"",chefe:"",datas:"",obs:""},
    {mes:"novembro",data:"07/11",dia:"sáb.",atividade:"Normal Sede",categoria:"",chefe:"Sampei e Mariana",datas:"",obs:""},
    {mes:"novembro",data:"14/11",dia:"sáb.",atividade:"Externa (a confirmar)",categoria:"",chefe:"",datas:"15 - Proclamação da República",obs:"BAILE ASSOCIACAO"},
    {mes:"novembro",data:"20/11",dia:"sex.",atividade:"Feriado Consciência Negra",categoria:"",chefe:"",datas:"Consciência Negra",obs:""},
    {mes:"novembro",data:"21/11",dia:"sáb.",atividade:"Emenda Feriado",categoria:"",chefe:"",datas:"",obs:""},
    {mes:"novembro",data:"28/11",dia:"sáb.",atividade:"Normal Sede - Roca de Conselho",categoria:"",chefe:"Angelita e Jefferson",datas:"",obs:""},
    {mes:"dezembro",data:"06/12",dia:"dom.",atividade:"Bonenkai",categoria:"Local",chefe:"",datas:"",obs:""}
  ],
  presenca: {
    datas: ["31/01","07/02","14/02","21/02","28/02","07/03","14/03","21/03","28/03","04/04","11/04","18/04","25/04","02/05","09/05","16/05","23/05","30/05","06/06","13/06","20/06","27/06","01/08","08/08","15/08","22/08","29/08","05/09","12/09","19/09","26/09","03/10","10/10","17/10","24/10","31/10","07/11","14/11","21/11","28/11"],
    membros: [
      {nome:"ALEX HWANG",reg:["P","A","P","P","P","P","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"ANA BEATRIZ MEGUMI HARASAKI",reg:["P","P","P","P","P","A","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"CAIO HIDEKI RODRIGUES UKON",reg:["P","P","A","A","P","A","P","A","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"CAIO KAZUKI ISHIY",reg:["","P","P","P","P","P","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"CAROLINA HARUMI HIRAOKA",reg:["","P","A","P","P","P","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"CAROLINA NAOMI ITIKAWA NAKAMURA",reg:["P","P","P","A","P","P","P","A","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"DANIEL MARIANO COUTINHO SOUSA",reg:["P","P","P","P","P","P","P","FJ","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"ENZO NAGADO",reg:["A","A","P","P","FJ","P","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"ERIC RYU SHINTANI KOJO",reg:["P","P","P","P","P","P","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"HENRY RYU TAKAHASHI KITAMURA",reg:["P","P","P","P","A","P","A","P","","","A","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"JULIA MIE TACHIBANA",reg:["","P","A","A","P","P","P","P","","","A","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"LETICIA LUMI TAKAHASHI KITAMURA",reg:["P","P","P","P","A","P","P","P","","","A","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"LIA SAORI TAGINI",reg:["P","P","P","P","P","P","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"LÍVIA YUI AKAMINE",reg:["P","P","A","A","P","P","P","A","","","A","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"LUCAS MARIANO COUTINHO SOUSA",reg:["P","P","P","P","P","P","P","A","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"LUCAS MASAKI ISHIY",reg:["P","P","P","P","P","P","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"LUCAS NORIO YAMADA KIMURA",reg:["P","P","P","P","P","P","P","P","","","A","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"LUCAS SUBARU OYAMA",reg:["P","P","P","P","P","P","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"LUCCA JUN MAIA YORINORI",reg:["A","P","P","P","P","FJ","P","A","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"LUIZA KIMI COSTIUC YAMACHIRA",reg:["P","P","P","P","P","P","P","P","","","A","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"LUIZA NAOMI FERNANDES FUJINO",reg:["P","FJ","A","A","P","A","P","FJ","","","A","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"MARIANA AYUMI HARASAKI",reg:["P","P","P","P","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"MIA TANIGUCHI",reg:["P","A","P","P","A","P","P","A","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"MIGUEL KNISS RODRIGUES",reg:["FJ","P","P","P","P","P","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"OLIVIA NAOMI WATANABE REZZANI",reg:["P","P","P","P","P","A","P","A","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"PEDRO SHUNJI RODRIGUES UKON",reg:["P","P","A","A","P","P","P","A","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"RAFAEL KENZO PENIN NISHIZAKI",reg:["","P","A","A","A","P","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"SABRINA SAYURI KOBAYASHI CAVALCANTE",reg:["","P","P","P","A","P","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"THOMAS AKIRA KANO MIYAGI",reg:["P","P","P","P","P","A","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]},
      {nome:"TIAGO JUN NAKAMURA OKUMA",reg:["P","P","P","P","FJ","P","P","P","","","P","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]}
    ]
  },
  especialidades: [
    {nome:'Alex',esp:'Natação',nivel:1,data:'',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Ana Beatriz Harasaki',esp:'Grafite',nivel:2,data:'',comprado:'OK',entregue:'Ok',avaliador:''},
    {nome:'Analu',esp:'Plantas Medicinais',nivel:3,data:'',comprado:'OK',entregue:'Sim',avaliador:''},
    {nome:'Mariana Harasaki',esp:'Maquete',nivel:2,data:'',comprado:'OK',entregue:'Sim',avaliador:''},
    {nome:'Caio',esp:'Maquete',nivel:1,data:'29/03',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Lucas Masaki',esp:'Video Game',nivel:2,data:'29/03',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Lucca',esp:'Volei',nivel:1,data:'26/04/2025',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Lucca Jun',esp:'Ciclismo',nivel:1,data:'',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Luisa Hina',esp:'Prevencao de Saude',nivel:1,data:'',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Mari Harasaki',esp:'Danca',nivel:2,data:'26/04/2025',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Mariana Harasaki',esp:'Grafite',nivel:2,data:'',comprado:'OK',entregue:'ok',avaliador:''},
    {nome:'Mariana Harasaki',esp:'Ciclismo',nivel:1,data:'29/03',comprado:'OK',entregue:'ok',avaliador:''},
    {nome:'Masaki',esp:'Animais Peconhentos',nivel:2,data:'26/04/2025',comprado:'OK',entregue:'',avaliador:''},
    {nome:'Mia',esp:'Natação',nivel:1,data:'',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Thomas',esp:'Origami',nivel:1,data:'29/03',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Yui',esp:'Babá',nivel:1,data:'',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Yui',esp:'Genealogia',nivel:1,data:'29/03',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Luisa Hina',esp:'Ciclismo',nivel:1,data:'29/03',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Luisa Hina',esp:'Insígnia do Aprender',nivel:0,data:'',comprado:'OK',entregue:'OK',avaliador:''},
    {nome:'Lucca Jun',esp:'Tênis',nivel:1,data:'05/07',comprado:'NÃO',entregue:'OK',avaliador:''},
    {nome:'Lucca Jun',esp:'Compostagem',nivel:1,data:'05/07',comprado:'NÃO',entregue:'OK',avaliador:''},
    {nome:'Lucas Kenzo',esp:'História do Escotismo',nivel:1,data:'05/07',comprado:'NÃO',entregue:'OK',avaliador:''},
    {nome:'Mariana Harasaki',esp:'Cone Sul',nivel:0,data:'05/07',comprado:'OK',entregue:'OK',avaliador:''}
  ],
  matilhas: {
    Amarela: ['THOMAS','CAIO UKON','LUCCA','MASAKI','DANIEL S.','NORIO','PEDRO','RAFAEL'],
    Branca: ['ALEX','ERIC','MIA','LUCAS S.','HENRY','ENZO','CAIO ISHIY'],
    Cinza: ['LUIZA KIMI','LIA','OLIVIA','YUI','CAROL NAOMI','JULIA','CAROL'],
    Preta: ['SUBARU','TIAGO','LETICIA','LUIZA NAOMI','BIA','MIGUEL','SABRINA']
  },
  cargos: {
    Amarela: {primo:'', segundo:''},
    Branca:  {primo:'', segundo:''},
    Cinza:   {primo:'', segundo:''},
    Preta:   {primo:'', segundo:''}
  },
  comunicados: [],
  confirmacoes: {},
  caixa: [],
  pontuacao: {
    Amarela: {jogos: 0, formacao: 0, comportamento: 0},
    Branca:  {jogos: 0, formacao: 0, comportamento: 0},
    Cinza:   {jogos: 0, formacao: 0, comportamento: 0},
    Preta:   {jogos: 0, formacao: 0, comportamento: 0}
  },
  avisos_internos: [],
  todos_chefia: []
};

// Exporta o estado para uso global
window.state = state;

// Made with Bob
